/* Design: Carta de Serviços de Itupeva — serviços em cartões legíveis, campos padronizados e consulta rápida por área. */
import { useMemo, useState } from "react";
import { BookOpen, CheckCircle2, ChevronDown, FileText, Search } from "lucide-react";
import OuvidoriaLayout from "@/components/OuvidoriaLayout";
import rawCarta from "@/data/carta-servicos.txt?raw";

type Service = { area: string; setor: string; service: string; description: string; audience: string; channels: string; deadline: string; free: string; documents: string; steps: string };
const services: Service[] = [
  { area: "Educação", setor: "Matrículas e Vagas", service: "Matrícula em Creche Municipal (CEMEB)", description: "Inscrição de crianças de 0 a 3 anos em creches municipais, conforme disponibilidade de vagas e critérios legais.", audience: "Pais, mães ou responsáveis por crianças de 0 a 3 anos.", channels: "Secretaria Escolar, Secretaria Municipal de Educação e sistema eletrônico, quando disponível.", deadline: "Conforme calendário e disponibilidade de vagas.", free: "Sim", documents: "Certidão de nascimento, CPF, comprovante de residência e documentos do responsável.", steps: "Inscrição → análise da documentação → classificação → convocação → efetivação da matrícula." },
  { area: "Educação", setor: "Matrículas e Vagas", service: "Matrícula em Escola Municipal de Educação Básica", description: "Matrícula de alunos do Ensino Fundamental, do 1º ao 9º ano, conforme zoneamento e disponibilidade.", audience: "Pais ou responsáveis.", channels: "Secretaria Escolar ou Secretaria Municipal de Educação.", deadline: "Imediato, havendo vaga.", free: "Sim", documents: "Certidão de nascimento, CPF, comprovante de residência, histórico escolar e documentos do responsável.", steps: "Solicitação → conferência documental → verificação de vaga → efetivação da matrícula." },
  { area: "Educação", setor: "Matrículas e Vagas", service: "Pré-Matrícula Online", description: "Realização da pré-matrícula por sistema eletrônico do Município.", audience: "Pais ou responsáveis.", channels: "Sistema eletrônico do Município.", deadline: "Conforme calendário oficial.", free: "Sim", documents: "Dados pessoais da criança e do responsável.", steps: "Preenchimento eletrônico → envio dos dados → validação → convocação para documentos." },
  { area: "Educação", setor: "Transporte Escolar", service: "Solicitação de Transporte Escolar Gratuito", description: "Cadastro para utilização do transporte escolar gratuito, conforme os critérios legais.", audience: "Alunos que atendam aos critérios legais.", channels: "Secretaria Escolar ou Departamento de Transporte Escolar.", deadline: "Até 15 dias úteis.", free: "Sim", documents: "Comprovante de residência e documentos do aluno e responsável.", steps: "Solicitação → análise dos critérios → deferimento → inclusão na rota." },
  { area: "Educação", setor: "Alimentação Escolar", service: "Solicitação de Dieta Especial na Merenda Escolar", description: "Solicitação de alimentação especial para alunos com restrições alimentares.", audience: "Alunos com restrições alimentares.", channels: "Secretaria Escolar.", deadline: "Até 10 dias úteis após a documentação.", free: "Sim", documents: "Laudo médico atualizado e formulário específico.", steps: "Protocolo → análise do nutricionista → elaboração do cardápio → comunicação à escola." },
  { area: "Educação", setor: "Apoio Pedagógico Especializado", service: "Atendimento Educacional Especializado (AEE)", description: "Atendimento para alunos com deficiência, TEA, TGD ou altas habilidades/superdotação.", audience: "Alunos público da Educação Especial.", channels: "Unidade Escolar, SME ou Núcleo de Educação Especial.", deadline: "Conforme avaliação técnica.", free: "Sim", documents: "Laudos, quando houver, relatórios pedagógicos e documentos escolares.", steps: "Encaminhamento → avaliação → definição do atendimento → acompanhamento." },
  { area: "Educação", setor: "Documentos Escolares", service: "2ª Via de Histórico Escolar", description: "Emissão da segunda via do histórico escolar.", audience: "Ex-alunos ou responsáveis.", channels: "Secretaria Escolar ou Secretaria Escolar Centralizada.", deadline: "Até 5 dias úteis.", free: "Sim", documents: "Documento de identificação.", steps: "Solicitação → localização do prontuário → emissão → entrega." },
  { area: "Assuntos Jurídicos e Fundiários", setor: "Regularização Fundiária", service: "Regularização Fundiária", description: "Processo de regularização de núcleos urbanos informais, irregulares ou clandestinos, incluindo análise, vistorias, atos administrativos e emissão da CRF.", audience: "Proprietários, possuidores, ocupantes, moradores e interessados.", channels: "Atendimento presencial, Protocolo Geral, SEI e Ouvidoria.", deadline: "Variável conforme a complexidade e a documentação.", free: "Gratuito, ressalvados custos cartorários previstos em lei.", documents: "Documento com foto, CPF, comprovante de residência, renda e documentos de posse ou propriedade.", steps: "Protocolo → análise documental → estudos técnicos → projetos → atos administrativos → CRF → Cartório de Registro de Imóveis." },
  { area: "Assuntos Jurídicos e Fundiários", setor: "Regularização Fundiária", service: "Verificação de Loteamento Irregular", description: "Fiscalização e verificação de loteamentos irregulares ou clandestinos existentes no Município.", audience: "Munícipes, proprietários, possuidores e interessados.", channels: "Ouvidoria, atendimento presencial, Protocolo Geral e SEI.", deadline: "Variável conforme a ocorrência e as diligências.", free: "Gratuito.", documents: "Documento de identificação ou indicação precisa do local e informações da irregularidade.", steps: "Recebimento → análise preliminar → vistoria → relatório técnico → medidas administrativas ou encaminhamento." },
  { area: "Assuntos Jurídicos e Fundiários", setor: "PROCON", service: "Atendimento Procon", description: "Registro de reclamações contra fornecedores, mediação de conflitos de consumo e orientação sobre direitos do consumidor.", audience: "Consumidores e fornecedores.", channels: "Atendimento presencial.", deadline: "De 30 a 60 dias corridos.", free: "Gratuito, ressalvadas despesas decorrentes de obrigações legais.", documents: "Documentos da relação de consumo, identificação, CPF e comprovante de residência.", steps: "Atendimento → registro → CIP → notificação → tentativa de solução → conciliação, quando necessária." },
  { area: "Assuntos Jurídicos e Fundiários", setor: "DETRAN", service: "Atendimento DETRAN", description: "Serviços descentralizados do DETRAN-SP, como documentos de veículos, licenciamento, transferência, débitos e pontuação.", audience: "Pessoas maiores de 18 anos e proprietários de veículos.", channels: "Atendimento presencial.", deadline: "Até 5 dias úteis, conforme o serviço.", free: "Atendimento gratuito; serviços podem ter taxas legais.", documents: "CNH, RG, CPF, comprovante de residência, CRLV e comprovantes de pagamento, quando aplicável.", steps: "Atendimento → conferência documental → pagamento de taxas, quando devido → processamento → emissão." },
  { area: "Assuntos Jurídicos e Fundiários", setor: "Geral", service: "Informações sobre Leis", description: "Orientação jurídica básica sobre leis municipais, decretos e normas aplicáveis, sem emissão de parecer ou consultoria individual.", audience: "População em geral.", channels: "Ouvidoria, telefone, atendimento presencial, e-mail, Protocolo Geral e SEI.", deadline: "Até 15 dias.", free: "Gratuito.", documents: "Não há exigência, salvo quando necessários para contextualização.", steps: "Recebimento → análise → pesquisa da legislação → orientação → resposta." },
  { area: "Gabinete — Defesa Civil", setor: "Defesa Civil – Prevenção", service: "Vistoria de Risco de Deslizamento em Área de Encosta", description: "Vistoria técnica para avaliação de risco geológico em encostas, taludes ou locais com possibilidade de deslizamento.", audience: "Qualquer pessoa.", channels: "Ouvidoria, telefone 156, WhatsApp da Defesa Civil e (11) 4591-1213.", deadline: "Atendimento imediato; resposta em até 15 dias.", free: "Gratuito.", documents: "Documento de identificação, localização exata e telefone para contato.", steps: "Recebimento → encaminhamento → vistoria → parecer técnico → interdição, quando necessária." },
  { area: "Gabinete — Defesa Civil", setor: "Defesa Civil – Prevenção", service: "Vistoria de Risco em Imóvel", description: "Vistoria técnica para avaliação de risco estrutural em imóvel ameaçado por desabamento, erosão ou outros fatores.", audience: "Proprietário, morador, vizinho ou interessado.", channels: "Ouvidoria, telefone 156, WhatsApp da Defesa Civil e (11) 4591-1213.", deadline: "Atendimento imediato; resposta em até 15 dias.", free: "Gratuito.", documents: "Documento de identificação, localização exata e telefone para contato.", steps: "Recebimento → encaminhamento → vistoria → parecer → interdição, quando necessária." },
  { area: "Gabinete — Ouvidoria", setor: "Ouvidoria", service: "Recebimento de reclamação", description: "Recebimento, análise e encaminhamento de reclamações relacionadas aos serviços públicos e ao atendimento municipal.", audience: "Qualquer usuário de serviço público.", channels: "Portal eOuve, telefone 156, WhatsApp institucional e atendimento no Agiliza Itupeva.", deadline: "Até 30 dias, prorrogável por mais 30 dias mediante justificativa.", free: "Gratuito.", documents: "Informações sobre o fato; identificação e contato quando desejados. Manifestação anônima admitida conforme o canal.", steps: "Manifestação → registro e protocolo → análise → apuração, quando cabível → resposta → encerramento." },
  { area: "Gabinete — Ouvidoria", setor: "Ouvidoria", service: "Recebimento de denúncia", description: "Recebimento de comunicações sobre irregularidades, ilícitos, crimes ou atos de corrupção relacionados à Administração Pública Municipal.", audience: "Qualquer pessoa.", channels: "Portal eOuve, telefone 156, WhatsApp institucional e atendimento presencial.", deadline: "Resposta ou encaminhamento conforme a natureza e a complexidade do caso.", free: "Gratuito.", documents: "Descrição precisa dos fatos, local, datas, documentos ou evidências disponíveis.", steps: "Recebimento → registro → análise preliminar → encaminhamento → apuração, quando cabível." },
  { area: "Gabinete — Ouvidoria", setor: "Ouvidoria", service: "Sugestão, elogio ou solicitação", description: "Recebimento e encaminhamento de sugestões, elogios e solicitações de providências ou serviços específicos.", audience: "Qualquer usuário de serviço público.", channels: "Portal eOuve, telefone 156, WhatsApp institucional e atendimento presencial.", deadline: "Até 30 dias, prorrogável por mais 30 dias quando aplicável.", free: "Gratuito.", documents: "Descrição da sugestão, elogio ou solicitação e dados necessários ao encaminhamento.", steps: "Recebimento → registro e protocolo → encaminhamento → resposta ou providência → encerramento." },
  { area: "Gabinete — Ouvidoria", setor: "Ouvidoria", service: "Serviço de Informação ao Cidadão — SIC", description: "Recebimento e processamento de pedidos de acesso a informações públicas sob guarda da Prefeitura, conforme a Lei de Acesso à Informação.", audience: "Qualquer pessoa física ou jurídica.", channels: "SIC, canais eletrônicos oficiais e atendimento presencial.", deadline: "Resposta imediata ou em até 20 dias, prorrogáveis por mais 10 dias.", free: "Gratuito, ressalvados custos de reprodução previstos em lei.", documents: "Pedido de informação claro e preciso; identificação e contato conforme o canal.", steps: "Recebimento → registro → busca e análise → resposta → recurso, quando cabível." },
];
const areas = ["Todas", ...Array.from(new Set(services.map((item) => item.area)))];

export default function CartaServicosPage() {
  const [query, setQuery] = useState("");
  const [activeArea, setActiveArea] = useState("Todas");
  const normalized = query.trim().toLocaleLowerCase("pt-BR");
  const filtered = useMemo(() => services.filter((item) => (activeArea === "Todas" || item.area === activeArea) && (!normalized || Object.values(item).join(" ").toLocaleLowerCase("pt-BR").includes(normalized))), [activeArea, normalized]);
  const areaCount = new Set(filtered.map((item) => item.area)).size;
  return <OuvidoriaLayout><div className="mx-auto max-w-[1200px]"><header className="mb-8"><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#D78B1D]"><span className="h-px w-6 bg-[#D78B1D]" />Serviços públicos</div><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="font-display text-4xl font-semibold tracking-tight text-[#173B5E] md:text-5xl">Carta de Serviços ao Usuário</h1><p className="mt-3 max-w-3xl text-[16px] leading-7 text-[#5E707A]">Consulte cada serviço por área, setor, canais de atendimento, prazo, documentos, gratuidade e etapas.</p></div><div className="shrink-0 rounded-2xl border border-[#F1D99A] bg-[#FFF8E8] px-5 py-4 text-sm leading-6 text-[#805D13]"><strong>Versão inicial</strong><br />Validação pelos órgãos responsáveis antes da publicação definitiva.</div></div></header>
<section className="rounded-2xl border border-[#E4DED2] bg-white/85 p-5 shadow-[0_12px_30px_rgba(23,59,94,0.05)] sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><label className="relative flex-1"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[#71818B]" size={19} /><span className="sr-only">Buscar serviço</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por serviço, área, canal ou documento" className="h-12 w-full rounded-xl border border-[#DCE3E4] bg-[#FAF9F5] pl-11 pr-4 text-sm text-[#173B5E] outline-none transition focus:border-[#00549D] focus:ring-4 focus:ring-[#DCECF8]" /></label><div className="flex items-center gap-2 text-sm font-bold text-[#526873]"><FileText size={18} className="text-[#00549D]" />{filtered.length} serviços · {areaCount} áreas</div></div><div className="mt-5 flex flex-wrap gap-2">{areas.map((area) => <button key={area} onClick={() => setActiveArea(area)} className={`rounded-full px-4 py-2 text-sm font-bold transition ${activeArea === area ? "bg-[#00549D] text-white" : "bg-[#EDF3F5] text-[#526873] hover:bg-[#DCECF8]"}`}>{area}</button>)}</div></section>
<div className="mt-8 grid gap-5 md:grid-cols-2">{filtered.map((item) => <article key={`${item.area}-${item.service}`} className="overflow-hidden rounded-2xl border border-[#E4DED2] bg-white/85 shadow-[0_12px_30px_rgba(23,59,94,0.04)]"><div className="border-b border-[#E4DED2] bg-[#FAF9F5] p-5"><div className="flex items-start gap-3"><CheckCircle2 className="mt-1 shrink-0 text-[#0A8F4D]" size={21} /><div><div className="text-xs font-bold uppercase tracking-widest text-[#71818B]">{item.area}</div><h2 className="mt-2 font-display text-2xl font-semibold leading-tight text-[#173B5E]">{item.service}</h2><div className="mt-2 inline-flex rounded-full bg-[#DCECF8] px-3 py-1 text-xs font-bold text-[#00549D]">{item.setor}</div></div></div></div><div className="space-y-4 p-5 text-sm leading-6 text-[#526873]"><p>{item.description}</p><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-[#F5F7F6] p-3"><strong className="block text-xs uppercase tracking-wide text-[#71818B]">Público-alvo</strong><span>{item.audience}</span></div><div className="rounded-xl bg-[#F5F7F6] p-3"><strong className="block text-xs uppercase tracking-wide text-[#71818B]">Prazo</strong><span>{item.deadline}</span></div><div className="rounded-xl bg-[#F5F7F6] p-3"><strong className="block text-xs uppercase tracking-wide text-[#71818B]">Canais</strong><span>{item.channels}</span></div><div className="rounded-xl bg-[#F5F7F6] p-3"><strong className="block text-xs uppercase tracking-wide text-[#71818B]">Gratuidade</strong><span>{item.free}</span></div></div><details className="group rounded-xl border border-[#DCE3E4] bg-white"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 font-bold text-[#00549D]"><span>Documentos e etapas</span><ChevronDown size={17} className="transition group-open:rotate-180" /></summary><div className="grid gap-4 border-t border-[#DCE3E4] px-4 py-4 sm:grid-cols-2"><div><strong className="block text-xs uppercase tracking-wide text-[#71818B]">Documentos</strong><p>{item.documents}</p></div><div><strong className="block text-xs uppercase tracking-wide text-[#71818B]">Etapas</strong><p>{item.steps}</p></div></div></details></div></article>)}</div>{filtered.length === 0 && <div className="mt-6 rounded-2xl border border-dashed border-[#B8C8CE] bg-white/70 p-10 text-center"><Search className="mx-auto text-[#71818B]" size={28} /><h2 className="mt-4 font-display text-2xl font-semibold text-[#173B5E]">Nenhum serviço encontrado</h2><p className="mt-2 text-sm text-[#71818B]">Tente buscar por outro termo ou selecione “Todas”.</p></div>}
<details className="mt-8 rounded-2xl border border-[#D7E7E6] bg-[#EAF4F2] p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 font-display text-2xl font-semibold text-[#173B5E]"><span><BookOpen className="mr-2 inline-block text-[#00549D]" size={21} />Conteúdo integral da versão anexada</span><ChevronDown size={20} /></summary><div className="mt-5 max-h-[520px] overflow-auto rounded-xl bg-white/80 p-5"><pre className="whitespace-pre-wrap break-words font-sans text-xs leading-6 text-[#526873]">{rawCarta}</pre></div></details><footer className="mt-8 rounded-xl border-2 border-[#00549D] bg-[#EAF4F2] px-5 py-4 text-sm leading-6 text-[#173B5E]"><strong>Importante:</strong> esta é uma versão inicial da Carta de Serviços ao Usuário. Os dados, prazos e canais devem ser validados e atualizados pelos órgãos responsáveis antes da publicação definitiva.</footer></div></OuvidoriaLayout>;
}
