/* Design: página institucional completa da Ouvidoria de Itupeva — ordem institucional definida pelo usuário, banners juntos e nota de acessibilidade destacada ao final. */
import { Accessibility, ExternalLink, FileText, HeartHandshake, MapPin, MessageCircle, Phone, Scale, ShieldCheck, Users } from "lucide-react";
import OuvidoriaLayout from "@/components/OuvidoriaLayout";

const channels = [{ title: "Telefone", value: "156", icon: Phone }, { title: "WhatsApp", value: "4591-8100", icon: MessageCircle }, { title: "Presencial", value: "Agiliza Itupeva", detail: "Avenida Itália, 661 — Jardim São Vicente", icon: MapPin }];
const types = [["Reclamações", "Insatisfações com serviços públicos ou atendimento."], ["Denúncias", "Irregularidades, crimes ou atos de corrupção."], ["Sugestões", "Propostas de melhoria para a gestão municipal."], ["Elogios", "Reconhecimento a bons serviços prestados."], ["Solicitações", "Pedidos de providências ou serviços específicos."]];
const team = [["Samuel Deividi Sobral Brigia", "Ouvidor-Geral"], ["Márcio José Arias", "Diretor"], ["Valdete Cardoso", "Atendente"], ["Elisangela A. S. Gonzales", "Atendente"]];
const laws = [["Lei Federal nº 12.527/2011", "Lei de Acesso à Informação (LAI).", "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm"], ["Lei Federal nº 13.460/2017", "Direitos do usuário do serviço público.", "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/lei/l13460.htm"], ["Lei Federal nº 13.709/2018", "Lei Geral de Proteção de Dados Pessoais.", "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm"], ["Lei Municipal nº 1.896/2012", "Cria a Ouvidoria Pública Municipal de Itupeva.", "https://leis.org/municipais/sp/itupeva/lei/lei-ordinaria/2012/1896/lei-ordinaria-n-1896-2012-cria-a-ouvidoria-publica-municipal-de-itupeva-e-da-outras?termo=1896"], ["Decreto Municipal nº 2.950/2018", "Regulamenta o acesso a informações no município.", "https://leismunicipais.com.br/a/sp/i/itupeva/decreto/2018/295/2950/decreto-n-2950-2018-dispoe-sobre-a-regulamentacao-do-acesso-a-informacoes-previsto-na-lei-federal-n-12527-de-18-de-novembro-de-2011-e-da-outras-providencias?q=2950"], ["Decreto nº 4.190/2026", "Regulamenta a LGPD no âmbito municipal.", "https://leis.org/prefeitura/sp/itupeva/lei/decreto/2026/4190/decreto-n-4190-2026-dispoe-sobre-a-regulamentacao-da-lei-federal-n-13709-de-14-de-agosto-de-2018-lei-geral-de-protecao-de-dados-pessoais-lgpd-no-ambito-da-administracao-municipal-direta-e-indireta-do-poder-executivo-municipal"], ["Decreto nº 4.194/2026", "Institui a política geral de proteção de dados pessoais de Itupeva.", "https://leis.org/prefeitura/sp/itupeva/lei/decreto/2026/4194-decreto-4194-2026-institui-a-politica-geral-de-protecao-de-dados-pessoais-no-ambito-da-administracao-municipal-direta-e-indireta-do-poder-executivo-municipal-de-itupeva"]];

export default function OuvidoriaPage() {
  return <OuvidoriaLayout><div className="mx-auto max-w-[1200px]"><header className="mb-8"><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#D78B1D]"><span className="h-px w-6 bg-[#D78B1D]" />Informações institucionais</div><h1 className="font-display text-4xl font-semibold tracking-tight text-[#173B5E] md:text-5xl">Ouvidoria Municipal</h1><p className="mt-2 max-w-3xl text-[16px] leading-7 text-[#5E707A]">A Ouvidoria é o canal da Prefeitura de Itupeva para ouvir a população, receber manifestações e encaminhar pedidos de providências sobre os serviços públicos.</p></header>

<section><h2 className="font-display text-3xl font-semibold text-[#173B5E]">Canais de atendimento</h2><div className="mt-4 grid gap-4 md:grid-cols-4">{channels.map(({ title, value, detail, icon: Icon }) => <div key={title} className="rounded-2xl border border-[#E4DED2] bg-white/80 p-6"><Icon className="text-[#00549D]" size={22} /><div className="mt-6 text-xs font-bold uppercase tracking-widest text-[#71818B]">{title}</div><div className="mt-2 font-display text-2xl font-semibold text-[#173B5E]">{value}</div>{detail && <p className="mt-2 text-sm leading-6 text-[#71818B]">{detail}</p>}</div>)}<div className="rounded-2xl bg-[#173B5E] p-6 text-white"><ExternalLink className="text-[#F0C433]" size={22} /><div className="mt-6 text-xs font-bold uppercase tracking-widest text-[#C8DBE2]">Online</div><a href="https://eouve.com.br/#/" target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-2 font-display text-2xl font-semibold hover:text-[#F0C433]">Portal eOuve <ExternalLink size={18} /></a></div></div></section>

<section className="mt-8 rounded-2xl border border-[#E4DED2] bg-white/80 p-6 sm:p-8"><h2 className="font-display text-3xl font-semibold text-[#173B5E]">Manifestações da Ouvidoria</h2><p className="mt-2 text-sm leading-6 text-[#71818B]">Canal para solicitar, reclamar, denunciar, elogiar ou sugerir sobre os serviços da Prefeitura.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{types.map(([title, text]) => <div key={title} className="rounded-xl border-l-4 border-[#F0C433] bg-[#FAF9F5] p-4"><h3 className="font-bold text-[#00549D]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#5E707A]">{text}</p></div>)}</div><div className="mt-6 rounded-xl bg-[#FFF8E8] p-4 text-sm leading-6 text-[#805D13]"><strong>Prazo Ouvidoria:</strong> resposta conclusiva em até 30 dias, prorrogável por mais 30 dias mediante justificativa.</div></section>

<section className="mt-8"><div className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-[#F1D99A] bg-[#FFF8E8] p-6"><HeartHandshake className="text-[#D78B1D]" size={24} /><h3 className="mt-5 font-display text-2xl font-semibold text-[#173B5E]">Denúncia de Violência contra Mulheres</h3><p className="mt-3 text-sm leading-6 text-[#805D13]">Canal especializado para acolher denúncias de violência contra mulheres, com atendimento humanizado e sigilo total.</p></div><div className="rounded-2xl border border-[#D9C7E8] bg-[#F7F0FB] p-6"><Scale className="text-[#76509A]" size={24} /><h3 className="mt-5 font-display text-2xl font-semibold text-[#3D2B52]">Combate à Discriminação Racial</h3><p className="mt-3 text-sm leading-6 text-[#5E476E]">Registre situações de racismo, injúria racial ou tratamento desigual para encaminhamento e apuração pelos canais competentes.</p></div><div className="rounded-2xl border border-[#B8D6DE] bg-[#F0F8FA] p-6"><Accessibility className="text-[#00549D]" size={24} /><h3 className="mt-5 font-display text-2xl font-semibold text-[#173B5E]">Atendimento à Pessoa com Deficiência</h3><p className="mt-3 text-sm leading-6 text-[#526873]">Informe barreiras de acesso, falta de acessibilidade ou necessidade de atendimento inclusivo. A página oferece recursos em Libras, Voz e Texto.</p></div></div></section>

<section className="mt-8 rounded-2xl border border-[#E4DED2] bg-white/80 p-6 sm:p-8"><h2 className="font-display text-3xl font-semibold text-[#173B5E]">SIC — Serviço de Informação ao Cidadão</h2><p className="mt-3 text-sm leading-6 text-[#526873]">O SIC atende pedidos de dados, atos, contratos e informações de interesse público sob a guarda da Prefeitura. Inclui despesas, gastos, notas fiscais, licitações, contratos, convênios, decretos, estrutura administrativa e dados de servidores.</p><div className="mt-5 rounded-xl bg-[#FAF9F5] p-4 text-sm leading-6 text-[#5E707A]"><strong>Prazo SIC:</strong> resposta imediata ou em até 20 dias, prorrogáveis por mais 10 dias mediante justificativa. Em caso de discordância ou falta de resposta, é possível recorrer em até 10 dias após o prazo.</div><a href="/sic" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#00549D] px-4 py-3 text-sm font-extrabold text-white">Acessar página do SIC <ExternalLink size={16} /></a></section>

<section className="mt-8 rounded-2xl border border-[#D7E7E6] bg-[#EAF4F2] p-6 sm:p-8"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 text-[#0A8F4D]" size={23} /><div><h2 className="font-display text-3xl font-semibold text-[#173B5E]">Protocolos, sigilo e LGPD</h2><p className="mt-2 text-sm leading-6 text-[#526873]">A pessoa pode escolher como deseja se relacionar com a Ouvidoria. A identificação não deve ser confundida com a exposição pública dos dados.</p></div></div><div className="mt-6 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-white/75 p-5"><h3 className="font-bold text-[#00549D]">Identificada</h3><p className="mt-2 text-sm leading-6 text-[#5E707A]">Dados informados para acompanhamento direto.</p></div><div className="rounded-xl bg-white/75 p-5"><h3 className="font-bold text-[#00549D]">Sigilosa</h3><p className="mt-2 text-sm leading-6 text-[#5E707A]">Identidade preservada e restrita à equipe de apuração.</p></div><div className="rounded-xl bg-white/75 p-5"><h3 className="font-bold text-[#00549D]">Anônima</h3><p className="mt-2 text-sm leading-6 text-[#5E707A]">Sem identificação, com acompanhamento via número de protocolo.</p></div></div><p className="mt-5 text-sm leading-6 text-[#2E7563]">Os dados são tratados conforme a LGPD — Lei nº 13.709/2018 — com segurança e confidencialidade.</p><div className="mt-5 rounded-xl border border-[#B8D6DE] bg-white/70 p-4 text-sm leading-6 text-[#173B5E]"><strong>Responsável pelos dados pessoais (DPO):</strong> Márcio José da Silva.</div></section>

<section className="mt-8 rounded-2xl border border-[#E4DED2] bg-white/80 p-6 sm:p-8"><div className="flex items-center gap-3"><Users className="text-[#00549D]" size={23} /><h2 className="font-display text-3xl font-semibold text-[#173B5E]">Nossa Equipe</h2></div><p className="mt-2 text-sm leading-6 text-[#71818B]">Servidores capacitados para garantir atendimento ao cidadão.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{team.map(([name, role]) => <div key={name} className="rounded-xl bg-[#FAF9F5] p-4"><div className="font-bold text-[#173B5E]">{name}</div><div className="mt-2 text-sm text-[#71818B]">{role}</div></div>)}</div><div className="mt-6 rounded-xl border border-[#D7E7E6] bg-[#EAF4F2] p-4 text-sm leading-6 text-[#2E7563]"><strong>Responsável pela Ouvidoria e SIC:</strong> Samuel Deividi Sobral Brigia, Ouvidor-Geral.</div></section>

<section className="mt-8 rounded-2xl border border-[#E4DED2] bg-white/80 p-6 sm:p-8"><div className="flex items-center gap-3"><FileText className="text-[#00549D]" size={23} /><h2 className="font-display text-3xl font-semibold text-[#173B5E]">Documentos e orientações</h2></div><div className="mt-6 grid gap-3 md:grid-cols-3"><a href="https://itupeva.sp.gov.br/cartas-de-servicos" target="_blank" rel="noreferrer" className="rounded-xl border border-[#E4DED2] bg-[#FAF9F5] p-5 hover:border-[#00549D]"><strong className="text-[#173B5E]">Cartas de Serviços ao Usuário</strong><p className="mt-2 text-sm leading-6 text-[#71818B]">Guia completo sobre serviços prestados pela Prefeitura.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#00549D]">Visualizar <ExternalLink size={15} /></span></a><a href="https://ecrie.com.br/sistema/conteudos/arquivo/a_77_0_1_14072026125122.pdf" target="_blank" rel="noreferrer" className="rounded-xl border border-[#E4DED2] bg-[#FAF9F5] p-5 hover:border-[#00549D]"><strong className="text-[#173B5E]">Manual de Procedimentos da Ouvidoria</strong><p className="mt-2 text-sm leading-6 text-[#71818B]">Normas, fluxos e procedimentos de atendimento.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#00549D]">Visualizar <ExternalLink size={15} /></span></a><a href="https://ecrie.com.br/sistema/conteudos/arquivo/a_77_0_1_30032026110729.pdf" target="_blank" rel="noreferrer" className="rounded-xl border border-[#E4DED2] bg-[#FAF9F5] p-5 hover:border-[#00549D]"><strong className="text-[#173B5E]">Relatório Anual de Gestão</strong><p className="mt-2 text-sm leading-6 text-[#71818B]">Transparência sobre atividades e resultados da Ouvidoria.</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#00549D]">Visualizar <ExternalLink size={15} /></span></a></div></section>

<section className="mt-8 rounded-2xl border border-[#E4DED2] bg-white/80 p-6 sm:p-8"><h2 className="font-display text-3xl font-semibold text-[#173B5E]">Base legal</h2><p className="mt-2 text-sm leading-6 text-[#71818B]">Consulte as normas federais e municipais relacionadas à Ouvidoria, ao acesso à informação e à proteção de dados.</p><div className="mt-6 grid gap-3 md:grid-cols-2">{laws.map(([title, text, href]) => <a key={title} href={href} target="_blank" rel="noreferrer" className="rounded-xl border border-[#E4DED2] bg-[#FAF9F5] p-4 hover:border-[#00549D]"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-[#173B5E]">{title}</strong><ExternalLink size={15} className="shrink-0 text-[#00549D]" /></div><p className="mt-2 text-xs leading-5 text-[#71818B]">{text}</p></a>)}</div></section><div className="mt-8 rounded-xl border-2 border-[#00549D] bg-[#EAF4F2] px-5 py-4 text-sm leading-6 text-[#173B5E]"><strong>Acessibilidade e fonte:</strong> Acessibilidade garantida em Libras, Voz e Texto. Conteúdo institucional consultado no <a className="font-bold text-[#00549D] underline" href="https://www.itupeva.sp.gov.br/ouvidoria-municipal/" target="_blank" rel="noreferrer">portal oficial da Prefeitura de Itupeva</a>.</div></div></OuvidoriaLayout>;
}
