/* Design: páginas institucionais da Ouvidoria de Itupeva — cartões claros, métricas agregadas e ações orientadas. */
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, ArrowRight, Check, Download, ExternalLink, Info, Search, ShieldCheck, Target } from "lucide-react";
import OuvidoriaLayout from "@/components/OuvidoriaLayout";

const secretarias = ["Gabinete do Prefeito", "Vice-Prefeito", "Chefia de Gabinete", "Assuntos Jurídicos e Fundiários", "Desenvolvimento Social", "Educação", "Fazenda", "Gestão Pública", "Guarda-Civil Municipal", "Indústria, Comércio e Desenvolvimento Econômico", "Infraestrutura e Manutenção", "Saúde", "Governo", "Obras, Planejamento e Mobilidade Urbana", "Esportes, Lazer e Cultura", "Turismo, Agricultura e Meio Ambiente"];
const indicators = [{ name: "Índice de resolutividade", definition: "Percentual de demandas que receberam uma solução considerada satisfatória ou resolvida.", reading: "Quanto maior, melhor.", source: "Resolveu? / CGU" }, { name: "Satisfação média", definition: "Percentual de avaliações positivas registradas após o atendimento.", reading: "Quanto maior, melhor.", source: "Pesquisa de satisfação" }, { name: "Dentro do prazo", definition: "Percentual de respostas enviadas dentro do prazo definido para o atendimento.", reading: "Quanto maior, melhor.", source: "Fala.BR" }, { name: "Tempo médio de resposta", definition: "Média de dias entre o registro e a resposta ao cidadão.", reading: "Quanto menor, melhor.", source: "Fala.BR" }, { name: "Registros avaliados", definition: "Quantidade total de registros considerados no período selecionado.", reading: "Mostra o volume do período.", source: "Fala.BR" }, { name: "Distribuição por tipo", definition: "Participação de solicitações, reclamações, denúncias, sugestões, elogios e simplificações.", reading: "Ajuda a entender a demanda.", source: "Resolveu? / CGU" }];

function PageTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mb-8"><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#D78B1D]"><span className="h-px w-6 bg-[#D78B1D]" />{eyebrow}</div><h1 className="font-display text-4xl font-semibold tracking-tight text-[#173B5E] md:text-5xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-[16px] leading-7 text-[#5E707A]">{description}</p>}</div>; }
function ActionButton({ children }: { children: React.ReactNode }) { return <button onClick={() => alert("Ação demonstrativa — será conectada aos dados oficiais.")} className="flex items-center gap-2 rounded-lg bg-[#00549D] px-4 py-3 text-sm font-extrabold text-white hover:bg-[#0A6BB8]">{children}</button>; }

type ReportMetric = { name: string; registered: number; concluded: number; open: number; outside: number | null; resolution: number | null };

export function ReportsPage() {
  const [period, setPeriod] = useState("Últimos 12 meses");
  const [start, setStart] = useState("");
  const [end, setEnd] = useState("");
  const [metrics, setMetrics] = useState<ReportMetric[]>([]);
  useEffect(() => {
    let active = true;
    const load = () => {
      const saved = localStorage.getItem("falabr-metrics");
      const request = saved ? Promise.resolve(JSON.parse(saved)) : Promise.reject(new Error("Nenhuma planilha carregada"));
      request.then((data) => {
        const names: string[] = data.meta?.secretarias || [];
        const monthKeys = Object.keys(data.mensal_dim || {}).sort();
        const latest = Object.keys(data.diario || {}).sort().at(-1) || `${monthKeys.at(-1) || ""}-28`;
        const rangeStart = period === "Período personalizado" ? (start || latest) : period === "Todo o período" ? `${monthKeys[0] || latest.slice(0, 7)}-01` : period === "Últimos 6 meses" ? `${monthKeys.slice(-6)[0] || latest.slice(0, 7)}-01` : period === "Últimos 3 meses" ? `${monthKeys.slice(-3)[0] || latest.slice(0, 7)}-01` : period === "Este mês" ? `${latest.slice(0, 7)}-01` : `${monthKeys.slice(-12)[0] || latest.slice(0, 7)}-01`;
        const rangeEnd = period === "Período personalizado" ? (end || latest) : latest;
        const months = monthKeys.filter((month) => month >= rangeStart.slice(0, 7) && month <= rangeEnd.slice(0, 7));
        const rows = names.map((name, index) => {
          const registered = months.reduce((sum, month) => sum + Number(data.mensal_dim?.[month]?.sec?.reg?.[index] || 0), 0);
          const concluded = months.reduce((sum, month) => sum + Number(data.mensal_dim?.[month]?.sec?.cc?.[index] || 0), 0);
          const storedOpen = months.reduce((sum, month) => sum + Number(data.mensal_dim?.[month]?.sec?.open?.[index] ?? 0), 0);
          const hasOpenData = months.some((month) => Array.isArray(data.mensal_dim?.[month]?.sec?.open));
          const open = hasOpenData ? storedOpen : Math.max(0, registered - concluded);
          const hasDeadlineData = months.some((month) => Array.isArray(data.mensal_dim?.[month]?.sec?.outside));
          const outside = hasDeadlineData ? months.reduce((sum, month) => sum + Number(data.mensal_dim?.[month]?.sec?.outside?.[index] || 0), 0) : null;
          return { name, registered, concluded, open, outside, resolution: registered ? (concluded / registered) * 100 : null };
        });
        if (active) setMetrics(rows);
      }).catch(() => { if (active) setMetrics([]); });
    };
    load();
    window.addEventListener("falabr-metrics-updated", load);
    return () => { active = false; window.removeEventListener("falabr-metrics-updated", load); };
  }, [period, start, end]);
  return <OuvidoriaLayout><div className="mx-auto max-w-[1200px]"><PageTitle eyebrow="Relatórios" title="Relatórios por secretaria" description="Acompanhe o volume de manifestações e o cumprimento dos prazos por secretaria no período selecionado." /><div className="mb-6 flex flex-col items-stretch justify-end gap-2 sm:items-end"><select value={period} onChange={(e) => setPeriod(e.target.value)} className="h-11 rounded-lg border border-[#DCE3E4] bg-white px-3 text-xs font-bold"><option>Últimos 12 meses</option><option>Últimos 6 meses</option><option>Últimos 3 meses</option><option>Este mês</option><option>Todo o período</option><option>Período personalizado</option></select>{period === "Período personalizado" && <div className="flex gap-2"><input type="date" value={start} onChange={(e) => setStart(e.target.value)} aria-label="Data inicial" className="h-9 rounded-lg border border-[#DCE3E4] bg-white px-2 text-xs" /><input type="date" value={end} onChange={(e) => setEnd(e.target.value)} aria-label="Data final" className="h-9 rounded-lg border border-[#DCE3E4] bg-white px-2 text-xs" /></div>}</div><div className="mb-5 flex items-center justify-between gap-4 border-b border-[#DCE3E4] pb-4"><div><h2 className="text-sm font-extrabold uppercase tracking-[0.14em] text-[#173B5E]">Indicadores do período</h2><p className="mt-1 text-xs text-[#71818B]">Os valores são atualizados a partir da planilha carregada.</p></div><div className="hidden items-center gap-4 text-xs text-[#71818B] sm:flex"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-[#D94736]" />Fora do prazo</span></div></div><div className="overflow-hidden rounded-2xl border border-[#DCE3E4] bg-white shadow-[0_8px_24px_rgba(23,59,94,0.04)]"><div className="grid min-w-[900px] grid-cols-[minmax(280px,1.7fr)_repeat(5,minmax(105px,1fr))] gap-4 border-b border-[#DCE3E4] bg-[#F5F8F8] px-6 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[#71818B] xl:grid"><div>Secretaria</div><div>Registrados</div><div>Concluídos</div><div>Abertos</div><div>Fora do prazo</div><div>Resolutividade</div></div><div className="divide-y divide-[#E8EEED]">
{metrics.map((item) => <div key={item.name} className="grid min-w-[900px] grid-cols-[minmax(280px,1.7fr)_repeat(4,minmax(105px,1fr))_minmax(110px,.8fr)] items-center gap-4 px-6 py-4 transition-colors hover:bg-[#F8FAFA]">
<div className="min-w-0"><h2 className="truncate text-sm font-semibold text-[#173B5E]">{item.name}</h2></div>
<div className="text-right tabular-nums text-sm font-semibold text-[#334E68]">{item.registered.toLocaleString("pt-BR")}</div>
<div className="text-right tabular-nums text-sm font-semibold text-[#334E68]">{item.concluded.toLocaleString("pt-BR")}</div>
<div className="text-right tabular-nums text-sm font-semibold text-[#334E68]">{item.open.toLocaleString("pt-BR")}</div>
<div className="text-right tabular-nums text-sm font-semibold text-[#B53B2F]">{item.outside === null ? "—" : item.outside.toLocaleString("pt-BR")}</div>
<div className="text-right tabular-nums text-sm font-semibold text-[#173B5E]">{item.resolution === null ? "—" : (item.resolution.toFixed(1).replace(".", ",") + "%")}</div>
</div>)}
</div></div>{metrics.length === 0 && <div className="rounded-2xl border border-dashed border-[#B8C8CE] bg-white/70 p-10 text-center text-sm text-[#71818B]">Carregando dados da fonte local…</div>}<div className="mt-7 flex justify-end"><ActionButton><Download size={16} /> Exportar relatório agregado</ActionButton></div></div></OuvidoriaLayout>; }

export function GoalsPage() { return <OuvidoriaLayout><div className="mx-auto max-w-[1200px]"><PageTitle eyebrow="Gestão" title="Metas e prazos" description="Acompanhe os compromissos de atendimento e veja onde a gestão precisa agir." /><div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-[#173B5E] p-6 text-white"><Target className="text-[#F0C433]" size={22} /><div className="mt-8 text-xs font-bold uppercase tracking-widest text-[#C8DBE2]">Meta de prazo</div><div className="mt-2 font-display text-4xl">90%</div><p className="mt-2 text-sm text-[#D5E1E6]">respostas dentro do prazo</p></div><div className="rounded-2xl border border-[#E4DED2] bg-white p-6"><Check className="text-[#0A8F4D]" size={22} /><div className="mt-8 text-xs font-bold uppercase tracking-widest text-[#71818B]">Resultado atual</div><div className="mt-2 font-display text-4xl">89,6%</div><p className="mt-2 text-sm text-[#71818B]">0,4 ponto abaixo da meta</p></div><div className="rounded-2xl border border-[#E4DED2] bg-[#FFF8E8] p-6"><Info className="text-[#B87800]" size={22} /><div className="mt-8 text-xs font-bold uppercase tracking-widest text-[#8A5B00]">Próxima revisão</div><div className="mt-2 font-display text-4xl">30 dias</div><p className="mt-2 text-sm text-[#8A5B00]">ciclo de acompanhamento</p></div></div><div className="mt-7 rounded-2xl border border-[#E4DED2] bg-white/75 p-6 sm:p-8"><h2 className="font-display text-2xl font-semibold">Indicadores monitorados</h2><div className="mt-6 space-y-5">{[["Prazo de resposta", 89.6, "Meta: 90%"], ["Resolutividade", 74, "Meta: 80%"], ["Satisfação", 84, "Meta: 85%"]].map(([label, value, meta]) => <div key={String(label)}><div className="mb-2 flex justify-between text-sm font-bold"><span>{label}</span><span>{value}% <span className="ml-2 text-xs font-normal text-[#71818B]">{meta}</span></span></div><div className="h-3 rounded-full bg-[#E8EDEB]"><div className="h-full rounded-full bg-[#00549D]" style={{ width: `${Number(value)}%` }} /></div></div>)}</div></div></div></OuvidoriaLayout>; }

export function SecretariasPage() { const [query, setQuery] = useState(""); const filtered = secretarias.filter((name) => name.toLowerCase().includes(query.toLowerCase())); return <OuvidoriaLayout><div className="mx-auto max-w-[1200px]"><PageTitle eyebrow="Estrutura municipal" title="Secretarias oficiais" description="Consulte as áreas da Prefeitura de Itupeva usadas como dimensões de acompanhamento da Ouvidoria." /><div className="relative mb-6 max-w-md"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8A9AA2]" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar secretaria" className="h-11 w-full rounded-lg border border-[#DCE3E4] bg-white pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-[#B8D6DE]" /></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((name, index) => <div key={name} className="flex items-center justify-between rounded-xl border border-[#E4DED2] bg-white/75 px-4 py-4"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#DCECF8] text-xs font-bold text-[#00549D]">{index + 1}</span><span className="text-sm font-bold">{name}</span></div><ArrowRight size={16} className="text-[#8A9AA2]" /></div>)}</div><div className="mt-7 rounded-xl border border-[#D7E7E6] bg-[#EAF4F2] p-4 text-sm text-[#2E7563]"><div className="flex gap-2"><ShieldCheck size={18} className="shrink-0" /><span>Fonte: <a className="font-bold underline" href="https://www.itupeva.sp.gov.br/secretarias" target="_blank" rel="noreferrer">portal oficial de Itupeva</a>.</span></div></div></div></OuvidoriaLayout>; }

export function IndicatorsPage() { return <OuvidoriaLayout><div className="mx-auto max-w-[1200px]"><PageTitle eyebrow="Orientação" title="Dicionário de indicadores" description="Entenda o significado de cada número antes de usar o painel para acompanhar resultados." /><div className="space-y-4">{indicators.map((item) => <div key={item.name} className="rounded-2xl border border-[#E4DED2] bg-white/75 p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 className="font-display text-2xl font-semibold">{item.name}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#5E707A]">{item.definition}</p></div><span className="rounded-full bg-[#DCECF8] px-3 py-1 text-xs font-bold text-[#00549D]">{item.reading}</span></div><div className="mt-4 flex items-center gap-2 text-xs text-[#71818B]"><Info size={14} />Fonte de referência: {item.source}</div></div>)}</div></div></OuvidoriaLayout>; }

export function NotFoundPage() { return <OuvidoriaLayout><div className="mx-auto max-w-xl py-20 text-center"><h1 className="font-display text-4xl">Página não encontrada</h1><p className="mt-3 text-[#71818B]">Use o menu para voltar ao painel da Ouvidoria de Itupeva.</p><Link href="/" className="mt-6 inline-flex items-center gap-2 font-bold text-[#00549D]"><ArrowLeft size={16} /> Voltar à visão geral</Link></div></OuvidoriaLayout>; }
