/* Design: identidade municipal de Itupeva — brasão oficial, azul institucional, verde, amarelo e ciano; navegação clara para a Ouvidoria. */
import { ReactNode, useState } from "react";
import { Link, useLocation } from "wouter";
import { BarChart3, BookOpen, CalendarClock, CircleHelp, FileBarChart, LayoutDashboard, Menu, Plus, ShieldCheck, Users, X } from "lucide-react";

const items = [
  { href: "/", label: "Visão geral", icon: LayoutDashboard },
  { href: "/registro", label: "Registrar manifestação", icon: Plus },
  { href: "/relatorios", label: "Relatórios por secretaria", icon: FileBarChart },
  { href: "/metas", label: "Metas e prazos", icon: CalendarClock },
];

export default function OuvidoriaLayout({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const [location] = useLocation();
  return <div className="min-h-screen bg-[#F7F5F0] text-[#173B5E]">
    <header className="sticky top-0 z-30 flex h-[76px] items-center justify-between border-b border-[#DCE3E4] bg-[#F7F5F0]/95 px-5 backdrop-blur-md lg:px-9"><div className="flex items-center gap-3"><button className="rounded-lg p-2 hover:bg-[#EDEAE1] lg:hidden" onClick={() => setOpen(true)} aria-label="Abrir menu"><Menu size={22} /></button><Link href="/" className="flex items-center gap-3"><div className="flex h-11 w-[118px] items-center justify-center rounded-lg bg-white px-2 shadow-[0_3px_0_#F0C433]"><img src="/manus-storage/itupeva-prefeitura-logo_a50aac52.png" alt="Itupeva Prefeitura" className="max-h-9 w-full object-contain" /></div><div><div className="font-display text-xl font-semibold leading-none tracking-tight text-[#00549D]">Ouvidoria <em className="text-[#0A8F4D] not-italic">Itupeva</em></div><div className="mt-1 text-[10px] font-bold uppercase tracking-[0.18em] text-[#71818B]">Painel de fiscalização</div></div></Link></div><div className="flex items-center gap-3"><button className="hidden items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-[#526873] hover:bg-[#EDEAE1] sm:flex"><CircleHelp size={17} /> Como ler os dados</button><div className="flex items-center gap-3 border-l border-[#DCE3E4] pl-3"><div className="hidden text-right sm:block"><div className="text-sm font-bold">Ouvidoria Municipal</div><div className="text-xs text-[#71818B]">Acesso institucional</div></div><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#D4E8E8] font-display font-semibold text-[#173B5E]">OM</div></div></div></header>
    <div className="flex"><aside className={`${open ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-40 w-[270px] border-r border-[#DCE3E4] bg-[#F7F5F0] px-5 py-24 transition-transform duration-200 lg:sticky lg:top-[76px] lg:h-[calc(100vh-76px)] lg:translate-x-0 lg:px-5 lg:py-8`}><button className="absolute right-4 top-5 rounded-md p-2 hover:bg-[#EDEAE1] lg:hidden" onClick={() => setOpen(false)} aria-label="Fechar menu"><X size={18} /></button><div className="mb-8 rounded-2xl bg-[#173B5E] p-5 text-white shadow-[0_10px_0_#E5A928]"><div className="mb-3 flex items-center gap-2 text-[#FFE9A8]"><ShieldCheck size={17} /><span className="text-xs font-bold uppercase tracking-widest">Visão institucional</span></div><p className="font-display text-[21px] leading-tight">Fiscalize resultados, não pessoas.</p><p className="mt-3 text-xs leading-5 text-[#D5E1E6]">Veja indicadores agregados da Prefeitura de Itupeva.</p></div><nav className="space-y-1" aria-label="Navegação principal"><p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#84929A]">Painel</p>{items.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition ${location === href ? "bg-[#DCECF8] text-[#173B5E]" : "text-[#526873] hover:bg-[#EDEAE1]"}`}><Icon size={18} className={location === href ? "text-[#24749A]" : "text-[#71818B]"} />{label}</Link>)}</nav><div className="mt-10 border-t border-[#DCE3E4] pt-6"><p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#84929A]">Fontes e orientação</p><Link href="/secretarias" className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${location === "/secretarias" ? "bg-[#DCECF8] text-[#173B5E]" : "text-[#526873] hover:bg-[#EDEAE1]"}`}><Users size={18} />Secretarias oficiais</Link><Link href="/indicadores" className={`mt-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${location === "/indicadores" ? "bg-[#DCECF8] text-[#173B5E]" : "text-[#526873] hover:bg-[#EDEAE1]"}`}><BookOpen size={18} />Dicionário de indicadores</Link><a href="https://centralpaineis.cgu.gov.br/visualizar/resolveu" target="_blank" rel="noreferrer" className="mt-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-[#526873] hover:bg-[#EDEAE1]"><BarChart3 size={18} />Painel Resolveu? da CGU</a></div></aside>{open && <div className="fixed inset-0 z-30 bg-[#173B5E]/30 lg:hidden" onClick={() => setOpen(false)} />}<main className="min-w-0 flex-1 px-5 py-8 lg:px-10 lg:py-10">{children}</main></div>
  </div>;
}
