/* Design: identidade municipal de Itupeva — brasão oficial, azul institucional, verde, amarelo e ciano; navegação clara para a Ouvidoria. */
import { ReactNode, useState } from "react";
import { Link, useLocation } from "wouter";
import { BarChart3, CircleHelp, FileBarChart, FileText, Info, LayoutDashboard, Menu, Plus, Settings, X } from "lucide-react";

const items = [
  { href: "/", label: "Visão geral", icon: LayoutDashboard },
  { href: "/registro", label: "Registrar Ouvidoria", icon: Plus },
  { href: "/sic", label: "Solicitar Informação SIC", icon: Plus },
  { href: "/relatorios", label: "Relatórios por secretaria", icon: FileBarChart },
];

export default function OuvidoriaLayout({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const [location] = useLocation();
  return <div className="min-h-screen bg-[#F7F5F0] text-[#173B5E]">
    <header className="sticky top-0 z-30 flex h-[76px] items-center justify-between border-b border-[#DCE3E4] bg-[#F7F5F0]/95 px-5 backdrop-blur-md lg:px-9"><div className="flex items-center gap-3"><button className="rounded-lg p-2 hover:bg-[#EDEAE1] lg:hidden" onClick={() => setOpen(true)} aria-label="Abrir menu"><Menu size={22} /></button><Link href="/" className="flex items-center gap-3"><div className="flex h-11 w-[118px] items-center justify-center rounded-lg bg-white px-2 shadow-[0_3px_0_#F0C433]"><img src={`${import.meta.env.BASE_URL}itupeva-prefeitura-logo.png`} alt="Itupeva Prefeitura" className="max-h-9 w-full object-contain" /></div><div><div className="font-display text-xl font-semibold leading-none tracking-tight text-[#00549D]">Ouvidoria <em className="text-[#0A8F4D] not-italic">Itupeva</em></div></div></Link></div><div className="flex items-center gap-3"><button className="hidden items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-[#526873] hover:bg-[#EDEAE1] sm:flex"><CircleHelp size={17} /> Como ler os dados</button></div></header>
    <div className="flex"><aside className={`${open ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-40 w-[270px] border-r border-[#DCE3E4] bg-[#F7F5F0] px-5 py-24 transition-transform duration-200 lg:sticky lg:top-[76px] lg:h-[calc(100vh-76px)] lg:translate-x-0 lg:px-5 lg:py-8`}><button className="absolute right-4 top-5 rounded-md p-2 hover:bg-[#EDEAE1] lg:hidden" onClick={() => setOpen(false)} aria-label="Fechar menu"><X size={18} /></button><nav className="space-y-1" aria-label="Navegação principal"><p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[0.2em] text-[#84929A]">Painel</p>{items.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition ${location === href ? "bg-[#DCECF8] text-[#173B5E]" : "text-[#526873] hover:bg-[#EDEAE1]"}`}><Icon size={18} className={location === href ? "text-[#24749A]" : "text-[#71818B]"} />{label}</Link>)}</nav><div className="mt-10 border-t border-[#DCE3E4] pt-6"><Link href="/ouvidoria" className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${location === "/ouvidoria" ? "bg-[#DCECF8] text-[#173B5E]" : "text-[#526873] hover:bg-[#EDEAE1]"}`}><Info size={18} />Informações da Ouvidoria</Link><Link href="/carta-servicos" className={`mt-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${location === "/carta-servicos" ? "bg-[#DCECF8] text-[#173B5E]" : "text-[#526873] hover:bg-[#EDEAE1]"}`}><FileText size={18} />Carta de Serviços</Link><Link href="/configuracoes" className={`mt-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${location === "/configuracoes" ? "bg-[#DCECF8] text-[#173B5E]" : "text-[#526873] hover:bg-[#EDEAE1]"}`}><Settings size={18} />Configurações</Link><a href="https://centralpaineis.cgu.gov.br/visualizar/resolveu" target="_blank" rel="noreferrer" className="mt-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-[#526873] hover:bg-[#EDEAE1]"><BarChart3 size={18} />Painel Resolveu? da CGU</a></div></aside>{open && <div className="fixed inset-0 z-30 bg-[#173B5E]/30 lg:hidden" onClick={() => setOpen(false)} />}<main className="min-w-0 flex-1 px-5 py-8 lg:px-10 lg:py-10">{children}</main></div>
  </div>;
}
